name: tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - run: |
          ls ${{ github.workspace }}
          cd ${{ github.workspace }}
          make test
